// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpletnoNarociloBaza;

#nullable disable

namespace SpletnoNarociloBaza.Migrations
{
    [DbContext(typeof(DBKontekst))]
    partial class DBKontekstModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("SpletnoNarociloBaza.Narocilo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CenaNarocila")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatumNarocila")
                        .HasColumnType("TEXT");

                    b.Property<int>("NarocnikId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NarocnikId");

                    b.ToTable("Narocila");
                });

            modelBuilder.Entity("SpletnoNarociloBaza.Narocnik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Narocniki");
                });

            modelBuilder.Entity("SpletnoNarociloBaza.Narocilo", b =>
                {
                    b.HasOne("SpletnoNarociloBaza.Narocnik", "Narocnik")
                        .WithMany("Narocila")
                        .HasForeignKey("NarocnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Narocnik");
                });

            modelBuilder.Entity("SpletnoNarociloBaza.Narocnik", b =>
                {
                    b.Navigation("Narocila");
                });
#pragma warning restore 612, 618
        }
    }
}
